# Generated by Django 4.1.3 on 2022-11-10 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50)),
                ('notification_time', models.TimeField(default=datetime.datetime.now)),
                ('notification_type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('servers_group', models.IntegerField(default=0)),
                ('servers_group_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
