# Generated by Django 4.1.3 on 2022-11-15 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermonitoring',
            name='notification_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
